---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    nfs.io/storage-path: test-helm-app
  name: pv-claim-helm
  labels:
    {{- include "first-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storage_class }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage_size }}
